project:
  type: website
  output-dir: docs

website:
  #open-graph: true
  title: "Tony Liang"
  search: false
  #site-url: https:/tonyliang19.com/  
  repo-url: https://github.com/tonyliang19/tonyliang19.github.io/
  repo-actions: [edit, issue] 
  #back-to-top-navigation: true

  # focus to read mode
  navbar:
    background: primary
    left:
      - text: "Home"
        file: index.qmd
      - text: "Projects" 
        href: project.qmd
      - text: Resume
        href: resume/index.qmd
      - sidebar:demos
      - sidebar:notes
    

    right:
      - href: 'https://www.linkedin.com/in/tonyliang19'
        text: "{{< iconify fa6-brands linkedin >}}"
      - href: 'https://github.com/tonyliang19'
        text: "{{< iconify fa6-brands github >}}"
      - href: 'https://www.instagram.com/tonyliang19/'
        text: "{{< iconify fa6-brands instagram >}}"
  sidebar:
  # dropdown for demos
  - id: demos
    title:  "Demos"
    style:  "docked"
    background: light
    collapse-level: 2
    contents: demos/*
  # dropdiwn for coding notes
  - id: notes
    title: "Quick Notes"
    style: "docked"
    background: light
    collapse-level: 2
    contents: notes/*
  page-footer:
    border: true
    right: "© 2023, Tony Liang"

format:
  html:
    theme:
      light: minty
      dark:  darkly #solar #darkly 
    code-copy: true
    code-fold: true
    code-link: true
    css: styles.css
    toc: true
    link-external-newwindow: true
    link-external-icon: true


#execute:
#  freeze: auto

