project:
  type: website
  output-dir: docs

website:
  title: "Tony Liang"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
#      light: journal
#      dark:  cyborg
    css: styles.css
    toc: true

execute:
  freeze: auto

