project:
  type: website
  output-dir: docs

bibliography: references.bib
website:
  page-navigation: true
  #open-graph: true
  title: "Tony Liang"
  
  search: false
  #site-url: https:/tonyliang19.com/  
  repo-url: https://github.com/tonyliang19/tonyliang19.github.io/
  repo-actions: [edit, issue] 
  #back-to-top-navigation: true

  # focus to read mode
  navbar:
    collapse: false
    pinned: false
    background: primary
    left:
      - text: "Home"
        file: index.qmd
      - text: "Projects" 
        href: projects/index.qmd
      - text: Resume
        href: resume/index.qmd
      - text: Demos
        href: demos/index.qmd
      - text: Notes
        href: notes/index.qmd
      # - text: Presentation
      #   href: presentations/
    

    right:
      - href: 'https://www.linkedin.com/in/tonyliang19'
        text: "{{< iconify fa6-brands linkedin >}}"
      - href: 'https://github.com/tonyliang19'
        text: "{{< iconify fa6-brands github >}}"
      - href: 'https://www.instagram.com/tonyliang19/'
        text: "{{< iconify fa6-brands instagram >}}"
  sidebar:
  # dropdown for demos
  - id: demos
    pinned: true
    title:  "Demos"
    style:  "docked"
    background: light
    collapse-level: 1
    contents: demos/**
  
  # dropdown for coding notes
  - id: notes
    pinned: true
    title: "Notes"
    style: docked
    #background: light
    collapse-level: 2
    contents: notes/**
  # footer in all pages
  page-footer:
    border: true
    right: "© 2023, Tony Liang"


format:
  html:
    # Control to show as border for code block
    code-block-border-left: "#31BAE9"
    code-block-bg: true
    # Copy button upon hover
    code-copy: hover
    # Folding codes
    code-fold: true
    # code-link: true
    code-summary: "Show the code"
    code-tools: false
    css: styles.css
    fontsize: 1.2em # change size for text here
    # change highlight of code
    highlight-style: github
    link-external-newwindow: true
    link-external-icon: true
    toc: true
    # optional to have number in sections
    number-sections: true
    theme:
      light: flatly
      dark:  darkly #solar #darkly 
    reference-location: document