project:
  type: website
  output-dir: docs

website:
  #open-graph: true
  title: "Tony Liang"
  search: false
  #site-url: https:/tonyliang19.com/  
  repo-url: https://github.com/tonyliang19/tonyliang19.github.io/
  repo-actions: [edit, issue] 
  navbar:
    background: primary
    left:
    #right:
      - href: index.qmd
        text: "Home"
      - href: project.qmd
        text: "Projects"
      - href: r_demo.qmd
        text: "R Demo"
      - href: python_demo.qmd
        text: "Python Demo"
        

  page-footer:
    border: false
    right: "© 2023, Tony Liang"

format:
  html:
    theme:
      light: minty
      dark:  superhero
    code-copy: true
    css: styles.css
    toc: true

#execute:
#  freeze: auto

