project:
  type: website
  output-dir: docs

website:
  #open-graph: true
  title: "Tony Liang"
  search: false
  #site-url: https:/tonyliang19.com/  
  repo-url: https://github.com/tonyliang19/tonyliang19.github.io/
  repo-actions: [edit, issue] 
  #back-to-top-navigation: true

  # focus to read mode
  navbar:
    background: primary
    left:
      - text: "Home"
        file: index.qmd
      - href: project.qmd
        text: "Projects"
      - href: resources/chunqing_tony_liang_resume.pdf
        text: Resume
      - sidebar:demos

    right:
      - href: 'https://www.linkedin.com/in/tonyliang19'
        text: "{{< iconify fa6-brands linkedin >}}"
      - href: 'https://github.com/tonyliang19'
        text: "{{< iconify fa6-brands github >}}"
      - href: https://www.instagram.com/tonyliang19/
        text: "{{< iconify fa6-brands instagram >}}"
  sidebar:
  - id: demos
    title:  "Demos"
    style:  "docked"
    background: light
    collapse-level: 2
    contents: demos/*

  page-footer:
    border: true
    right: "© 2023, Tony Liang"

format:
  html:
    theme:
      light: minty
      dark:  superhero
    code-copy: true
    code-link: true
    css: styles.css
    toc: true 
    link-external-newwindow: true
    link-external-icon: true
    

#execute:
#  freeze: auto

