project:
  type: website
  output-dir: docs

website:
  title: "Tony Liang"
  search: false
  navbar:
    background: primary
    left:
    #right:
      - href: index.qmd
        text: "Home"
      - href: r_demo.qmd
        text: "R Demo"
      - href: python_demo.qmd
        text: "Python Demo"

  page-footer:
    border: false
    right: "© 2023, Tony Liang"

format:
  html:
    theme:
      light: minty
      dark:  superhero
    css: styles.css
    toc: true

#execute:
#  freeze: auto

